@startuml DashboardUML
!define DARKBLUE
!include style.plantuml
hide circle
skinparam classAttributeIconSize 0

' Basisklasse
class Student {
    -student_id: str
    -name: str
    -start_date: date
}

class ModuleResult {
    -module_id: str
    -cp: int
    -grade: float
    -date_passed: date
}

together {
    class Goal {
        -goal_type: GoalType
        -target_value: float
        -adjustable: bool
        -duration_months: int
    }

    enum GoalType {
        deadline
        grade_avg
        cp_pace
    }
}   
' Aggregation: lose Verbindungen
' Student "1 " o-- "0..*" ModuleResult : has
' Student "1 " o-- "0..*" Goal : has
Student "1 " -- "0..*" ModuleResult
Student "1 " -- "1..*" Goal : has

' ' Komposition: fest verbaute Bestandteile
' Kaffeemaschine " 1" *-- "1" Bohnenbehaelter

' ' Vererbung
' PremiumKaffeemaschine -up-|> Kaffeemaschine

' ' Assoziation
' App "1 " -up-> "0..* " PremiumKaffeemaschine : steuert

@enduml